# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'SwiftyJSON'
  pod 'HydraAsync', '~> 1.0.0'

  # Pods for Twift

  target 'TwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end